--MySQL
# Method 1:
SELECT DISTINCT CITY
FROM STATION
WHERE LOWER(CITY) NOT REGEXP '^[aeiou]';

# Method 2:
SELECT DISTINCT CITY
FROM STATION
WHERE LOWER(CITY) NOT RLIKE '^[aeiou]';

# Method 3:
SELECT DISTINCT CITY FROM STATION
WHERE LOWER(CITY) REGEXP '^[^aeiou]';

# Method 4:
SELECT DISTINCT CITY FROM STATION
WHERE LOWER(CITY) RLIKE '^[^aeiou]';

--MS SQL Server
# Method 1:
SELECT DISTINCT CITY
FROM STATION
WHERE LOWER(CITY) NOT LIKE '[aeiou]%';

# Method 2:
SELECT DISTINCT CITY
FROM STATION
WHERE LOWER(CITY)  LIKE '[^aeiou]%';
