--MySQL
# Method 1:
SELECT DISTINCT CITY
FROM STATION
WHERE LOWER(CITY) NOT REGEXP '^[aeiou].*[aeiou]$';

# Method 2:
SELECT DISTINCT CITY
FROM STATION
WHERE LOWER(CITY) NOT RLIKE '^[aeiou].*[aeiou]$';

--MS SQL Server
SELECT DISTINCT CITY
FROM STATION
WHERE LOWER(CITY) NOT LIKE '[aeiou]%[aeiou]';
