--MySQL
SELECT CITY, LENGTH(CITY) AS short_city
FROM STATION
ORDER BY LENGTH(CITY), CITY
LIMIT 1;
SELECT CITY, LENGTH(CITY) AS long_city
FROM STATION
ORDER BY LENGTH(CITY) DESC, CITY
LIMIT 1;


--MS SQL Server
SELECT TOP 1 CITY, LEN(CITY) AS short_city
FROM STATION
ORDER BY LEN(CITY), CITY;
SELECT TOP 1 CITY, LEN(CITY) AS long_city
FROM STATION
ORDER BY LEN(CITY) DESC, CITY;
