--MySQL & MS SQL Server
# Method 1:
SELECT SUM(CITY.POPULATION)
FROM CITY 
JOIN COUNTRY ON CITY.COUNTRYCODE = COUNTRY.CODE
WHERE COUNTRY.CONTINENT = 'ASIA';

# Method 2:
SELECT SUM(CITY.POPULATION)
FROM CITY, COUNTRY 
WHERE CITY.COUNTRYCODE = COUNTRY.CODE
AND COUNTRY.CONTINENT = 'ASIA';
